### ISSUE TITLE
Error: 'dav'

### ISSUE THREAD

**Issue by MisterEffiks** [pamapa/python-fritzbox#4]
Hi,

i want to use this script to retrieve the address book from a Baïkal CardDAV server, but i only get the error
`Error: 'dav'`

With debug on, here's the output:

`download phonebook from http://192.168.2.242:81/baikal/card.php/addressbooks/USERNAME/default/
get_books(http://192.168.2.242:81/baikal/card.php/addressbooks/USERNAME/default/)
Error: 'dav'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/python_fritzbox-0.2-py3.4.egg/EGG-INFO/scripts/fritzboxphonebook.py", line 115, in <module>
    args.vip_groups, picture_path, debug=args.debug)
  File "/usr/local/lib/python3.4/dist-packages/python_fritzbox-0.2-py3.4.egg/fritzbox/CardDAV.py", line 100, in get_books
    xml = self._get_xml(session, url, settings, debug)
  File "/usr/local/lib/python3.4/dist-packages/python_fritzbox-0.2-py3.4.egg/fritzbox/CardDAV.py", line 40, in _get_xml
    if response.headers['DAV'].count('addressbook') == 0:
  File "/usr/local/lib/python3.4/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'dav'`

The command i use is this:

`fritzboxphonebook.py --webdav-url http://192.168.2.242:81/baikal/card.php/addressbooks/USERNAME/default/ --webdav-username USERNAME --webdav-password PASSWORD --save mybook.xml
`

The lighttpd-log from the Baïkal-Server shows the access:

`10.0.0.1 192.168.2.242:81 - [10/Jan/2018:11:12:57 +0000] "PROPFIND /baikal/card.php/addressbooks/USERNAME/default/ HTTP/1.1" 404 36 "-" "-"

10.0.0.4 192.168.2.242:81 - [10/Jan/2018:11:14:10 +0000] "PROPFIND /baikal/card.php/addressbooks/USERNAME/default/ HTTP/1.1" 404 36 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:45.0) Gecko/20100101 Thunderbird/45.8.0 Lightning/4.7.8"`

1st line: the script
2nd line: access from Thunderbird with SOGo Connector

Thanks,
Felix

**Comment by MisterEffiks** [comment]
Shame on me, updated php and Baïkal, now it works!
